### ISSUE TITLE
rust actix analytics library uses native-tls by default, unable to use rustls

### ISSUE THREAD

**Issue by 1zun4** [tom-draper/api-analytics#5]
Hello.

It is not possible to stop reqwest from using native-tls.
`reqwest = { version = "0.11", features = ["json", "blocking"] }`
defined here: https://github.com/tom-draper/api-analytics/blob/main/analytics/rust/actix/analytics/Cargo.toml

I prefer to use rustls-tls, which can be defined like this:
`reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "rustls-tls"] }`

A possible solution to this issue would add features to the analytics crate like this:
```toml
reqwest = { version = "0.11", default-features = false, features = ["json", "blocking"] }

...

[features]
default = ["native-tls"]

rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/default-tls"]
```
